### ISSUE TITLE
String literals start with wrong quotation marks

### ISSUE THREAD

**Issue by bonkf** [NLua/NLuaBox#1]
Some string literals in the example scripts start with `„` instead of `"`. This leads to parsing errors. My phone is set to English but I'm using a German keyboard in case that is relevant.

Example:
![image](https://user-images.githubusercontent.com/10628294/55511864-e8db1880-5661-11e9-84e2-53e6ab763ad8.png)

**Comment by viniciusjarina** [comment]
There is a bug on UIKit, so even when the SmartQuotes are disabled UIKit still repleaces `"` by `„`.
I will test using German keyboard.

This is the hack I had to do.
https://github.com/NLua/NLuaBox/blob/9ac6c5dada672ce7e2e4eaef59bf76bf87a4de96/NLuaBox/ViewControllers/CodeViewController.cs#L58

Is this `0x201E` ?

Thank you for the report.

**Comment by bonkf** [comment]
It is `0x201E`, yes.

**Comment by viniciusjarina** [comment]
Ok. I will fix this evening. 
Thank you @Reperator
